
services:

  db:
    image: postgres:16
    container_name: app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: christmas_gifts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d christmas_gifts"]
      interval: 3s
      timeout: 5s
      retries: 10

  migrate:
    image: golang:1.24-alpine
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/christmas_gifts?sslmode=disable
    volumes:
      # - ./backend/scripts/migrate.sh:/app/backend/scripts/migrate.sh
      - ./backend/scripts:/app/backend/scripts
      - ./backend/migrations:/app/backend/migrations
    command: >
      sh -c "
      apk add --no-cache bash &&
      chmod +x /app/backend/scripts/migrate.sh &&
      /app/backend/scripts/migrate.sh
      "

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
      target: dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s 
  
  frontend: 
    build: 
      context: ./frontend
      dockerfile: front.dockerfile
      target: dev
    environment: 
      VITE_API_URL: http://backend:8080
      #ajou de cette var d'env pour vite pour pas que essaie de communiquer avec localhost mais bien avec le backend pour le backend 
    depends_on:
      backend: 
        condition: service_healthy
    ports: 
      - "5173:5173"

  test-backend:
    build:
      context: ./backend
      dockerfile: dockerfile
      target: test
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
